name: Bug report
description: Report a problem with Roslyn
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        Before reporting make sure that Roslyn is updated to the latest version.

  - type: textarea
    attributes:
      label: "Description"
      description: "A comprehensive description of the problem you are reporting."
    validations:
      required: true

  - type: input
    attributes:
      label: "Neovim version"
      description: |
        Output of `nvim --version`
      placeholder: "v0.12.0-dev-1574+g8d6963a6a0"
    validations:
      required: true

  - type: input
    attributes:
      label: "Operating system and version"
      placeholder: "macOS 14.4, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected:"

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "Observed behavior (may optionally include logs, images, or videos)."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Minimal config"
      description: >
        Minimal(!) configuration necessary to reproduce the issue. Save this as
        `init.lua`.

        Please **DO NOT** include a package manager (such as `lazy.nvim`) in this.

        If this is not provided, the issue may be closed without notice.

        You may use `NVIM_APPNAME=roslyn_issue nvim` to test with a minimal config.
        Check out `:h $NVIM_APPNAME` for more info.
      render: Lua
      value: |
        for name, url in pairs{
          roslyn = "https://github.com/seblyng/roslyn.nvim",
          -- Add other plugins to reproduce the issue
        } do
          local install_path = vim.fn.fnamemodify("roslyn_issue/"..name, ":p")
          if vim.fn.isdirectory(install_path) == 0 then
            vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
          end
          vim.opt.runtimepath:append(install_path)
        end

        require("roslyn").setup{
          -- Add config options necessary to reproduce the issue
        }

        -- Add additional config necessary to reproduce the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Roslyn checkhealth"
      render: text
      description: >
        Please include the output of `:checkhealth roslyn`.
    validations:
      required: true
