---
name: lua_ls-typecheck

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          path: lua
          level: Warning
          configpath: ".luarc.json"
